services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: AIdea
      POSTGRES_PASSWORD: aidea1234
      POSTGRES_DB: AIdeaDB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
